/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.login.agente;

import com.github.britooo.looca.api.core.Looca;
import com.github.britooo.looca.api.group.sistema.Sistema;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author vitor.herculano
 */
public class loginJfame extends javax.swing.JFrame {

    /**
     * Creates new form loginJfame
     */
    public loginJfame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        descricao = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        subtitulo = new javax.swing.JLabel();
        iptSenha = new javax.swing.JTextField();
        iptEmail = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        btnEsqueceuSenha = new javax.swing.JButton();
        logoEmail = new javax.swing.JLabel();
        logoSenha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(15, 15, 15));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-totem-hub-_1_.png"))); // NOI18N

        descricao.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        descricao.setForeground(new java.awt.Color(255, 255, 0));
        descricao.setText("Visibilidade Técnica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descricao))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(logo)
            .addComponent(descricao)
        );

        titulo.setBackground(new java.awt.Color(0, 0, 0));
        titulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Login de Acesso");

        subtitulo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        subtitulo.setText("Entre com suas Credênciais:");

        iptSenha.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        iptSenha.setForeground(new java.awt.Color(204, 204, 204));
        iptSenha.setText("Insira sua senha");
        iptSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                iptSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                iptSenhaFocusLost(evt);
            }
        });

        iptEmail.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        iptEmail.setForeground(new java.awt.Color(204, 204, 204));
        iptEmail.setText("Insira seu e-mail");
        iptEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                iptEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                iptEmailFocusLost(evt);
            }
        });

        btnEntrar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnEsqueceuSenha.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnEsqueceuSenha.setText("Esqueceu sua Senha?");
        btnEsqueceuSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsqueceuSenhaActionPerformed(evt);
            }
        });

        logoEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-user-30.png"))); // NOI18N

        logoSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-password-30.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(subtitulo)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logoSenha, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnEsqueceuSenha)
                                .addGap(18, 18, 18)
                                .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(iptEmail)
                                .addComponent(iptSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)))
                        .addGap(45, 45, 45))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addComponent(subtitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iptEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoEmail))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(iptSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoSenha))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEsqueceuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEsqueceuSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsqueceuSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEsqueceuSenhaActionPerformed

    private void iptEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_iptEmailFocusGained
        // TODO add your handling code here:
        if (iptEmail.getText().equals("Insira seu e-mail")) {
            iptEmail.setText("");
            iptEmail.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_iptEmailFocusGained

    private void iptEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_iptEmailFocusLost
        // TODO add your handling code here:
        if (iptEmail.getText().equals("")) {
            iptEmail.setText("Insira seu e-mail");
            iptEmail.setForeground(new Color(153, 153, 153));
        }


    }//GEN-LAST:event_iptEmailFocusLost

    private void iptSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_iptSenhaFocusGained
        // TODO add your handling code here:
        if (iptSenha.getText().equals("Insira sua senha")) {
            iptSenha.setText("");
            iptSenha.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_iptSenhaFocusGained

    private void iptSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_iptSenhaFocusLost
        // TODO add your handling code here:

        if (iptSenha.getText().equals("")) {
            iptSenha.setText("Insira sua senha");
            iptSenha.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_iptSenhaFocusLost

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        // TODO add your handling code here:
        Looca looca = new Looca();
        Sistema sistema = looca.getSistema();
        String redirectURL;

        if ("".equals(iptEmail.getText()) || "".equals(iptSenha.getText())) {

            JOptionPane.showMessageDialog(null, "Campos em branco! Preencha corretamente.");

        } else if ("Insira seu e-mail".equals(iptEmail.getText()) || "Insira sua senha".equals(iptSenha.getText())) {

            JOptionPane.showMessageDialog(null, "Senha e/ou e-mail inválidos! Preencha corretamente.");

        } else {
            JOptionPane.showMessageDialog(null,"Login realizado com sucesso");

            JOptionPane.showMessageDialog(null,sistema);
           
            redirectURL = http://www.devmedia.com.br/;
            response.sendRedirect(redirectURL);
            
        }


    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginJfame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginJfame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginJfame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginJfame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginJfame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnEsqueceuSenha;
    private javax.swing.JLabel descricao;
    private javax.swing.JTextField iptEmail;
    private javax.swing.JTextField iptSenha;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logoEmail;
    private javax.swing.JLabel logoSenha;
    private javax.swing.JLabel subtitulo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
